# -*- coding: utf-8 -*-
"""Scrapping with zenrows.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Bi0C-7subu8gaXPkGtgUxX54HeyF7SF
"""

import time
import pandas as pd
import requests

## pip install zenrows

## from zenrows import ZenRowsClient

## client = ZenRowsClient("63b15ada725c13fdf1114f662b43060a2d925e95")

# 1. Your Zenscrape API Key (Get this from your Zenscrape dashboard)
ZENROWS_API_KEY = "15b5c0475a25859c656a37b3e1e8b2ecabe69671"
ZENROWS_ENDPOINT = "https://api.zenrows.com/v1/"

# 2. Base URL of the target website
base_target_url = "https://results.eci.gov.in/ResultAcGenMay2026/ConstituencywiseS22{}.htm"

all_tables = []

for page_num in range(1, 235):
    # Dynamically build the target URL for this iteration
    target_url = base_target_url.format(page_num)
    print(f"Scraping page {page_num}/234 via ZenRows...")

    # 3. Configure ZenRows parameters
    params = {
        "apikey": ZENROWS_API_KEY,
        "url": target_url,
        "mode": "auto",  # ZenRows Adaptive Stealth Mode (Automatically bypasses blocks)
        # "js_render": "true" # OPTIONAL: Uncomment if the table relies on JavaScript/React to load
    }

    try:
        # Route the request through ZenRows
        response = requests.get(ZENROWS_ENDPOINT, params=params, timeout=30)

        if response.status_code == 200:
            # Pass ZenRows' cleanly returned HTML straight into Pandas
            tables = pd.read_html(response.text)

            if tables:
                df = tables[0]  # Assuming the target table is the first one
                df["Source_Page"] = page_num  # Track data origin
                all_tables.append(df)
            else:
                print(f"No HTML tables found on page {page_num}")
        else:
            print(
                f"ZenRows API Error on page {page_num}. Status Code: {response.status_code}"
            )

    except Exception as e:
        print(f"An unexpected error occurred on page {page_num}: {e}")

    # Note: ZenRows manages proxy rotation for you, so you don't need a heavy time.sleep().
    # A short safety buffer is fine, or you can remove it entirely.
    time.sleep(0.5)

# 4. Consolidate and Save data
if all_tables:
    final_df = pd.concat(all_tables, ignore_index=True)
    final_df.to_csv("zenrows_tabular_data.csv", index=False)
    print(f"Success! Master file created with {len(final_df)} rows.")
else:
    print("Scraping completed, but no data was successfully extracted.")

df_from_csv = pd.read_csv('zenrows_tabular_data.csv')
display(df_from_csv.head())

print(all_tables)